### ISSUE TITLE
Build Results -> Next Result and Previous Result never work

### ISSUE THREAD

**Issue by evandrocoan** [rctay/sublime-text-2-buildview#26]
### Build Results -> Next Result and Previous Result never work

So, how to got these folks working:

![image](https://cloud.githubusercontent.com/assets/5332158/19460424/6024ad5a-94ba-11e6-85e3-151d794e32a3.png)

May be I am understanding they wrong, they are not the output results are they the error symbols?

**Comment by Erimus-Koo** [comment]
Sublime Text 4, and the same question. I'd remember that I'd press some key to display the previous, but I can't find it again, help please.

**Comment by rctay** [comment]
Hi @Erimus-Koo could you share some information:
1. what is the file extension that you are triggering Build for? 
2. what is the syntax/language of the file you are triggering Build for?
3. what is the Build System being used (if you manually selected one)?

Next / Previous result is dependant on the Build System defining a `file_regex` so that Next / Previous result (which is the navigation of files specified in the build output) works.

**Comment by Erimus-Koo** [comment]
1. what is the file extension that you are triggering Build for?
    `.py`  
    <img width="80" alt="image" src="https://user-images.githubusercontent.com/17139670/231957942-ff037398-2c0a-47ad-a6e5-53f45fee8759.png">

2. what is the syntax/language of the file you are triggering Build for?
    Python  
    <img width="172" alt="image" src="https://user-images.githubusercontent.com/17139670/231958150-4c153d56-6df4-46e4-ad98-23e04f0154bc.png">

3. what is the Build System being used (if you manually selected one)?
    Tools/Build System/Python  
    <img width="421" alt="image" src="https://user-images.githubusercontent.com/17139670/231958413-b8fec4e3-1f3b-4308-9bc2-c2ed84d02724.png">

---

And there are still "no more results".

I do remember it worked some days ago, but it has disappeared now.
